---
- name: Deploy Web Files
  hosts: repo
  
  tasks:
    - name: "deploy web files"
      copy:
        src: "{{ src_path }}/{{ content }}" 
        dest: "{{ dest_path }}"
        owner: ecorella
        group: ecorella
        mode: "0750"
#      with_items: "{{ content }}"
