---
- name: Deploy Web Files
  hosts: repo
  tasks:
    - name: "Deploy web files"
      ansible.builtin.copy:
        src: "{{ src_path }}/{{ item }}"
        dest: "{{ dest_path }}"
        owner: ecorella
        group: ecorella
        mode: "0750"
      with_items: "{{ content }}"
