---
- name: Setup a Jenkins Master Server
  hosts: jenkins
  become: true
  tasks:

   - name: Get repo file
     ansible.builtin.get_url:
      url: "{{ repo_url }}"
      dest: /etc/yum.repos.d/
      mode: '0644'


   - name: Import key
     ansible.builtin.rpm_key:
      state: present
      key: "{{ key_url }}"


   - name: Install packages
     ansible.builtin.dnf:
      name: "{{ packages }}"
      state: present
