---
- name: Setup a Jenkins Worker Server
  hosts: jenkins_agent
  become: yes

  tasks:

  - name: Create jenkins user
    user:
      name: jenkins
      comment: Jenkins Automation Server
      home: /var/lib/jenkins

  - name: Install Java 
    yum:
      name: java-11-openjdk.x86_64
      state: present
