---
- name: Playbook for resetting passwords
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: "Resetting password for user {{ target_user }}"
      ansible.builtin.user:
        name: "{{ target_user }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always
