---
- name: Playbook for resetting passwords
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: "Resetting password for user {{ target_user }}"
      user:
        name: "{{ target_user }}"
        password: "{{ new_password | password_hash('sha512') }}"
